repos:
  -   repo: local
      hooks:
        -   id: run-tests
            name: Run Tests Before Commit
            entry: ./run-tests.sh
            language: script
            pass_filenames: false
